name: benchmark-vfm-ss
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2025.8.3=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.4.0=py310h5eee18b_3
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.11.0=py310h397f862_1
  - openssl=3.0.17=h5eee18b_0
  - pandas=2.3.1=py310h277b779_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.19.1
      - flash-attn==2.8.3
      - fonttools==4.59.1
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitignore-parser==0.1.11
      - gitpython==3.1.45
      - grpcio==1.74.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-resources==6.5.2
      - ipykernel==6.29.4
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonargparse==4.27.7
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - lightning==2.2.1
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.6.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.3
      - pyyaml==6.0.2
      - pyzmq==27.0.1
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.12.0
      - sentry-sdk==2.35.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==0.9.16
      - tokenizers==0.15.2
      - torch==2.2.2
      - torchinfo==1.8.0
      - torchmetrics==1.8.1
      - torchvision==0.17.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.39.2
      - triton==2.2.0
      - typeshed-client==2.8.2
      - typing-extensions==4.14.1
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wandb==0.16.5
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.20.1